package com.tacs.tp1c2026.entities.enums;

public enum NotificationType {
    TRADE_PROPOSAL_RECEIVED,
    TRADE_PROPOSAL_ACCEPTED,
    TRADE_PROPOSAL_REJECTED,
    AUCTION_OFFER_RECEIVED,
    AUCTION_OFFER_ACCEPTED,
    AUCTION_OFFER_REJECTED,
    AUCTION_CANCELLED,
    AUCTION_ENDING_SOON,
    WANTED_CARD_AVAILABLE_IN_AUCTION,
    WANTED_CARD_AVAILABLE_IN_PUBLICATION
}
