spring.application.name=tp1c2026

#Agregao bd en memoria
# Configuraci�n b�sica de conexi�n
spring.datasource.url=jdbc:h2:mem:coleccionista_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar la consola web (para que puedas ver las tablas en el navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuraci�n de JPA / Hibernate
# Update: crea las tablas autom�ticamente basadas en tus clases @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Permite que la consola de H2 se vea si usas Spring Security (opcional)
spring.h2.console.settings.web-allow-others=true

app.bucket.count=10
app.scheduled.example.cron=0 0 * * * *