spring.application.name=tp1c2026

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/tacs_db}
spring.data.mongodb.database=${MONGO_DATABASE:tacs_db}

logging.level.org.springframework.data.mongodb=DEBUG